colorscheme PaperColor
set background=dark
set clipboard=unnamed,autoselect
set guioptions=eg

" Window size
set lines=30
"set columns=100

" change the cursor line color
highlight CursorLine guifg=#E19972

if has('multi_byte_ime')
  highlight Cursor guifg=NONE guibg=Green
  highlight CursorIM guifg=NONE guibg=Red
endif

" Read local setting.
if filereadable(expand('$HOME/.gvimrc_local'))
  source $HOME/.gvimrc_local
endif

